services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    networks:
      - cassandra-network
    environment:
      - CASSANDRA_CLUSTER_NAME=interview-service
      - CASSANDRA_SEEDS=cassandra-node1
      - HEAP_NEWSIZE=400M
      - MAX_HEAP_SIZE=1G
    ports:
      - "9042:9042"

networks:
  cassandra-network:
    driver: bridge
