version: '3'
services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    networks:
      - cassandra-network
    environment:
      - CASSANDRA_CLUSTER_NAME=interview-service
      - CASSANDRA_SEEDS=cassandra-node1
    ports:
      - "9042:9042"

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    networks:
      - cassandra-network
    environment:
      - CASSANDRA_CLUSTER_NAME=interview-service
      - CASSANDRA_SEEDS=cassandra-node1

  cassandra-node3:
    image: cassandra:latest
    container_name: cassandra-node3
    networks:
      - cassandra-network
    environment:
      - CASSANDRA_CLUSTER_NAME=interview-service
      - CASSANDRA_SEEDS=cassandra-node1

networks:
  cassandra-network:
    driver: bridge
